import { fileURLToPath } from "node:url";
import {
  LENSES,
  location,
  NO_FINDINGS_COPY,
  plainText,
  TIER_ORDER,
  TIER_WORD,
  type EvidenceView,
  type FindingView,
  type ModelNoteView,
  type ReportModel,
} from "./model.js";

/**
 * The PDF surface, a walker over the report model — the client-presentable
 * document, set in the SOW house style this project ports from
 * a sibling project's exporter. Every sentence, tier, glyph, ordering, and
 * disclosure rendered here is decided by `buildReportModel`; what this file
 * owns is typesetting — fonts, sizes, the rule, the footer, and where the
 * gray goes. Concealment arrives from the model as segments; this flat
 * surface joins them through `plainText` and renders the labels verbatim.
 *
 * pdfkit is loaded inside `renderPdf` with a dynamic `import()` and nowhere
 * else, so a run that never asks for a PDF never loads it — pinned by
 * `test/report/pdf.test.ts`, "imports pdfkit dynamically and nowhere
 * statically", which reads this file's source.
 *
 * Unlike the HTML's lens tabs and the Markdown's lens sections, this surface
 * is one numbered list in model order — a client reads a single ranked
 * document, with each finding's lens shown as a small caption rather than a
 * grouping. The model's walker rule allows this (order is preserved, nothing
 * is dropped), and `test/report/pdf.test.ts`, "renders every finding across
 * pages — none silently truncated", pins it across page breaks. `ReachView`
 * site lists are this surface's one density cut, exactly as they are the
 * terminal's and the Markdown's: a reach finding's body already states the
 * reference count, and the full site list stays on the HTML surface.
 */

/**
 * The embedded DejaVu family, committed under `fonts/` and shipped in the
 * npm package so the renderer works wherever the package is installed. The
 * accepted coverage trade: DejaVu covers Latin, Cyrillic, and Greek broadly,
 * but not CJK or other scripts — full-Unicode fonts cost tens of megabytes.
 */
const FONT_FILES = {
  sans: "DejaVuSans.ttf",
  bold: "DejaVuSans-Bold.ttf",
  oblique: "DejaVuSans-Oblique.ttf",
  mono: "DejaVuSansMono.ttf",
} as const;

/** Registered-font names, one per file in `FONT_FILES`. */
const SANS = "urtext-sans";
const BOLD = "urtext-sans-bold";
const OBLIQUE = "urtext-sans-oblique";
const MONO = "urtext-mono";

/**
 * Resolved relative to this module, so the same path works from `src/report/`
 * under tsx and from `dist/report/` in an installed package — both sit one
 * directory tree beside `fonts/`.
 */
function fontPath(file: string): string {
  return fileURLToPath(new URL(`../../fonts/${file}`, import.meta.url));
}

const MARGIN = 54;

const TITLE_SIZE = 20;
const HEADING_SIZE = 13;
const BODY_SIZE = 11;
const META_SIZE = 10;
const CAPTION_SIZE = 9;
const FOOTER_SIZE = 8;

/** Where the footer baseline sits, measured up from the page's bottom edge. */
const FOOTER_RISE = 36;

const GRAY = "#666666";
const BLACK = "#000000";

/** The one sentence every page's footer carries, beside the page number. */
const FOOTER_LINE = "Generated by urtext — every finding is labeled by its evidence tier";

const LENS_LABEL = new Map<string, string>(LENSES.map((l) => [l.key, l.label]));

type Doc = PDFKit.PDFDocument;

/** A bold-label/value meta line, the SOW house style's header idiom. */
function metaLine(doc: Doc, label: string, value: string): void {
  doc
    .font(BOLD)
    .fontSize(META_SIZE)
    .text(`${label}: `, { continued: true })
    .font(SANS)
    .text(value);
}

/**
 * A whole-line bold disclosure. The honesty-critical lines — "This review is
 * partial.", every `notes` entry, the filter note — all pass through here,
 * so no restyling can quiet one of them without quieting the style itself.
 */
function strongLine(doc: Doc, text: string): void {
  doc.font(BOLD).fontSize(META_SIZE).text(text);
}

function rule(doc: Doc): void {
  const y = doc.y;
  doc
    .moveTo(MARGIN, y)
    .lineTo(doc.page.width - MARGIN, y)
    .stroke();
  doc.moveDown();
}

/**
 * The only way model-authored text reaches this document: the attribution
 * line, then the prose, then the trust caveat, all from the one
 * `ModelNoteView` (see `./model.js`, where their inseparability is argued).
 * Like the HTML and the Markdown, not gated on a recorded model name: the
 * model's UNNAMED_MODEL fallback attribution shows instead, visibly
 * incomplete rather than absent.
 */
function modelNoteBlock(doc: Doc, note: ModelNoteView): void {
  doc.font(OBLIQUE).fontSize(META_SIZE).text(`unverified · ${note.model}`);
  doc.font(SANS).fontSize(BODY_SIZE).text(plainText(note.text));
  doc.font(OBLIQUE).fontSize(META_SIZE).text(note.caution);
}

function evidenceBlock(doc: Doc, ref: EvidenceView): void {
  doc.font(OBLIQUE).fontSize(CAPTION_SIZE).fillColor(GRAY).text(location(ref)).fillColor(BLACK);
  doc.font(MONO).fontSize(CAPTION_SIZE).text(plainText(ref.excerpt));
  doc.moveDown(0.5);
}

function findingSection(doc: Doc, finding: FindingView, ordinal: number): void {
  doc
    .font(BOLD)
    .fontSize(HEADING_SIZE)
    .text(
      `${ordinal}. ${finding.glyph} ${plainText(finding.headline)} [${finding.tier}]` +
        (finding.beyondIntent ? ` (${finding.beyondIntent})` : ""),
    );
  doc
    .font(SANS)
    .fontSize(CAPTION_SIZE)
    .fillColor(GRAY)
    .text(LENS_LABEL.get(finding.lens) ?? finding.lens)
    .fillColor(BLACK);
  doc.moveDown(0.5);
  for (const paragraph of finding.body) {
    doc.font(SANS).fontSize(BODY_SIZE).text(plainText(paragraph));
    doc.moveDown(0.5);
  }
  if (finding.modelNote) {
    modelNoteBlock(doc, finding.modelNote);
    doc.moveDown(0.5);
  }
  for (const ref of finding.evidence) {
    evidenceBlock(doc, ref);
  }
  doc.moveDown();
}

/**
 * Stamped onto every buffered page once the content is laid out — only then
 * is the page count known. The bottom margin is zeroed for the duration of
 * each stamp: pdfkit starts a fresh page for any text that lands inside the
 * margin, even absolutely positioned text, and a footer that adds a page —
 * itself footerless — would break "prints the footer on every page" in
 * `test/report/pdf.test.ts`.
 */
function stampFooters(doc: Doc): void {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    const savedBottom = doc.page.margins.bottom;
    doc.page.margins.bottom = 0;
    const y = doc.page.height - FOOTER_RISE;
    doc.font(SANS).fontSize(FOOTER_SIZE).fillColor(GRAY);
    doc.text(FOOTER_LINE, MARGIN, y, { lineBreak: false });
    doc.text(String(i + 1), MARGIN, y, {
      width: doc.page.width - MARGIN * 2,
      align: "right",
      lineBreak: false,
    });
    doc.fillColor(BLACK);
    doc.page.margins.bottom = savedBottom;
  }
}

export async function renderPdf(model: ReportModel): Promise<Buffer> {
  const { default: PDFDocument } = await import("pdfkit");

  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({ margin: MARGIN, bufferPages: true });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", (err: Error) => reject(err));

    doc.registerFont(SANS, fontPath(FONT_FILES.sans));
    doc.registerFont(BOLD, fontPath(FONT_FILES.bold));
    doc.registerFont(OBLIQUE, fontPath(FONT_FILES.oblique));
    doc.registerFont(MONO, fontPath(FONT_FILES.mono));

    doc.font(BOLD).fontSize(TITLE_SIZE).text("urtext review");
    doc.moveDown();

    metaLine(doc, "Generated", new Date().toISOString().slice(0, 10));
    metaLine(doc, "Range", model.scope);
    metaLine(doc, "Model", model.modelName ?? "not asked");
    metaLine(
      doc,
      "Evidence",
      TIER_ORDER.map((tier) => `${model.counts[tier]} ${TIER_WORD[tier]}`).join(" · "),
    );

    // The disclosures, every one, before the rule and the list: a reader has
    // to know what the review could not see before reading the findings and
    // concluding nothing else was found. Order matches the other surfaces:
    // provenance, the partial-review notes, coverage, then the filter note.
    if (model.provenance) {
      doc.font(SANS).fontSize(META_SIZE).text(model.provenance);
    }
    if (model.notes.length > 0) {
      // Gated on the model's `notes` exactly: non-empty means the review is
      // partial and this surface must say so, in the same sentence the
      // HTML's banner leads with.
      strongLine(doc, "This review is partial.");
      for (const note of model.notes) {
        strongLine(doc, note);
      }
    }
    if (model.coverageNote) {
      doc.font(SANS).fontSize(META_SIZE).text(model.coverageNote);
    }
    if (model.unanalyzedNote) {
      doc.font(SANS).fontSize(META_SIZE).text(model.unanalyzedNote);
    }
    if (model.generatedNote) {
      doc.font(SANS).fontSize(META_SIZE).text(model.generatedNote);
    }
    if (model.filterNote) {
      strongLine(doc, model.filterNote);
    }
    if (model.distributionNote) {
      strongLine(doc, model.distributionNote);
    }
    // Once per kind. Not bold: this is orientation, not a disclosure about
    // what the run did or did not do.
    for (const note of model.kindNotes) {
      doc.font(SANS).fontSize(META_SIZE).text(note);
    }
    // Whole-line bold, like every honesty-critical line on this surface:
    // never restyled away.
    if (model.beyondIntentLegend) {
      strongLine(doc, model.beyondIntentLegend);
    }
    // Below the notes and the legend, above the findings. Below the notes so
    // a partial-review disclosure is never pushed under a block that is not
    // itself a disclosure; below the legend for the reason the terminal and
    // Markdown use — the reader meets the badge's meaning before the block
    // that aggregates it.
    if (model.intentGap.length > 0) {
      strongLine(doc, `Not described by this change's messages (${model.intentGap.length})`);
      for (const e of model.intentGap) {
        doc
          .font(SANS)
          .fontSize(META_SIZE)
          .text(`[${e.tier}] ${plainText(e.label)}  ${e.file}:${e.line}`);
      }
      if (model.intentGapAttribution) {
        doc.font(SANS).fontSize(META_SIZE).text(model.intentGapAttribution);
      }
    }
    doc.moveDown();

    rule(doc);

    if (model.findings.length === 0) {
      doc.font(SANS).fontSize(BODY_SIZE).text(NO_FINDINGS_COPY);
    }
    for (const [index, finding] of model.findings.entries()) {
      findingSection(doc, finding, index + 1);
    }

    stampFooters(doc);
    doc.end();
  });
}
