import { Hono } from "hono";
import { cors } from "hono/cors";
import { sign, verify } from "hono/jwt";
import bcrypt from "bcryptjs";
import { HTTPException } from "hono/http-exception";

// ═══════════════════════════════════════════════════════════
// UserAuthAPI
// Generated by KLAR-IR Transpiler v0.1.0
// Generated at: 2026-03-13T00:54:54.654Z
//
// This file was compiled from a KLAR-IR semantic graph.
// Do not edit manually — modify the IR and recompile.
// ═══════════════════════════════════════════════════════════

// ── Models ────────────────────────────────────────────────

export interface User {
  id: string;
  email: string;
  name: string;
  password: string;
  role: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateUserInput {
  email: string;
  name: string;
  password: string;
  role: string;
}

export interface Post {
  id: string;
  title: string;
  body: string;
  authorId: string;
  published: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface CreatePostInput {
  title: string;
  body: string;
  authorId: string;
  published: boolean;
}

// ── Validation (from KLAR-IR constraints) ─────────────────

interface ValidationError {
  field: string;
  message: string;
}

function validateUser(input: Record<string, any>): ValidationError[] {
  const errors: ValidationError[] = [];
  if (input.email === undefined || input.email === null) {
    errors.push({ field: "email", message: "email is required" });
  }
  // Constraint: Must be a valid email address
  if (input.email !== undefined && !/^[^@]+@[^@]+\.[^@]+$/.test(String(input.email))) {
    errors.push({ field: "email", message: "Must be a valid email address" });
  }
  // Constraint: email must not be empty
  if (input.email !== undefined && String(input.email).length < 1) {
    errors.push({ field: "email", message: "email must not be empty" });
  }
  if (input.name === undefined || input.name === null) {
    errors.push({ field: "name", message: "name is required" });
  }
  // Constraint: Name must be at least 2 characters
  if (input.name !== undefined && String(input.name).length < 2) {
    errors.push({ field: "name", message: "Name must be at least 2 characters" });
  }
  // Constraint: Name must be at most 100 characters
  if (input.name !== undefined && String(input.name).length > 100) {
    errors.push({ field: "name", message: "Name must be at most 100 characters" });
  }
  if (input.password === undefined || input.password === null) {
    errors.push({ field: "password", message: "password is required" });
  }
  // Constraint: Password must be at least 8 characters
  if (input.password !== undefined && String(input.password).length < 8) {
    errors.push({ field: "password", message: "Password must be at least 8 characters" });
  }
  if (input.role === undefined || input.role === null) {
    errors.push({ field: "role", message: "role is required" });
  }
  // Constraint: Role must be 'user' or 'admin'
  if (input.role !== undefined && !["user","admin"].includes(input.role)) {
    errors.push({ field: "role", message: "Role must be 'user' or 'admin'" });
  }
  return errors;
}

function validatePost(input: Record<string, any>): ValidationError[] {
  const errors: ValidationError[] = [];
  if (input.title === undefined || input.title === null) {
    errors.push({ field: "title", message: "title is required" });
  }
  // Constraint: Title is required
  if (input.title !== undefined && String(input.title).length < 1) {
    errors.push({ field: "title", message: "Title is required" });
  }
  // Constraint: Title must be under 200 characters
  if (input.title !== undefined && String(input.title).length > 200) {
    errors.push({ field: "title", message: "Title must be under 200 characters" });
  }
  if (input.body === undefined || input.body === null) {
    errors.push({ field: "body", message: "body is required" });
  }
  // Constraint: Post body is required
  if (input.body !== undefined && String(input.body).length < 1) {
    errors.push({ field: "body", message: "Post body is required" });
  }
  if (input.authorId === undefined || input.authorId === null) {
    errors.push({ field: "authorId", message: "authorId is required" });
  }
  // Constraint: Author ID is required
  if (input.authorId !== undefined && String(input.authorId).length < 1) {
    errors.push({ field: "authorId", message: "Author ID is required" });
  }
  if (input.published === undefined || input.published === null) {
    errors.push({ field: "published", message: "published is required" });
  }
  return errors;
}

function validateRoute_POST__auth_register(input: Record<string, any>): ValidationError[] {
  const errors: ValidationError[] = [];
  if (input.email !== undefined && !/^[^@]+@[^@]+\.[^@]+$/.test(String(input.email))) {
    errors.push({ field: "email", message: "Valid email required" });
  }
  if (input.name !== undefined && String(input.name).length < 2) {
    errors.push({ field: "name", message: "name must be at least 2 characters" });
  }
  if (input.password !== undefined && String(input.password).length < 8) {
    errors.push({ field: "password", message: "Password must be at least 8 characters" });
  }
  return errors;
}

function validateRoute_POST__posts(input: Record<string, any>): ValidationError[] {
  const errors: ValidationError[] = [];
  if (input.title !== undefined && String(input.title).length < 1) {
    errors.push({ field: "title", message: "title must not be empty" });
  }
  if (input.title !== undefined && String(input.title).length > 200) {
    errors.push({ field: "title", message: "title must be at most 200 characters" });
  }
  if (input.body !== undefined && String(input.body).length < 1) {
    errors.push({ field: "body", message: "body must not be empty" });
  }
  return errors;
}


// ── Middleware ─────────────────────────────────────────────


// Request logger
function loggerMiddleware() {
  return async (c: any, next: any) => {
    const start = Date.now();
    const method = c.req.method;
    const path = c.req.path;

    await next();

    const duration = Date.now() - start;
    const status = c.res.status;
    console.log(`${method} ${path} → ${status} (${duration}ms)`);
  };
}

// Rate limiter: 100 requests per 60000ms window
const rateLimitStore = new Map<string, { count: number; resetAt: number }>();

function rateLimitMiddleware() {
  return async (c: any, next: any) => {
    const key = c.req.header("x-forwarded-for") || "unknown";
    const now = Date.now();
    const entry = rateLimitStore.get(key);

    if (!entry || now > entry.resetAt) {
      rateLimitStore.set(key, { count: 1, resetAt: now + 60000 });
    } else if (entry.count >= 100) {
      c.header("Retry-After", String(Math.ceil((entry.resetAt - now) / 1000)));
      return c.json({ error: "Rate limit exceeded" }, 429);
    } else {
      entry.count++;
    }

    await next();
  };
}

// JWT Auth middleware
const JWT_SECRET = process.env.JWT_SECRET;

function authMiddleware() {
  return async (c: any, next: any) => {
    const authHeader = c.req.header("Authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return c.json({ error: "Missing or invalid authorization header" }, 401);
    }

    try {
      const token = authHeader.slice(7);
      const payload = await verify(token, JWT_SECRET);
      c.set("user", payload);
      await next();
    } catch {
      return c.json({ error: "Invalid or expired token" }, 401);
    }
  };
}

// ── In-Memory Store (swap for real DB in production) ──────

const userStore = new Map<string, User>();
const postStore = new Map<string, Post>();

function generateId(): string {
  return crypto.randomUUID();
}

// ── Route Handlers ────────────────────────────────────────

// Register a new user account
// Effects: DB (findOne on User), DB (insert into User)
// Proofs:
//   ✓ no_plaintext_password: Password is hashed before storage via bcrypt [by_construction]
//   ✓ unique_email: Email uniqueness enforced by DB index + pre-check [by_constraint]
async function handle_post__auth_register(c: any) {
  try {
    const body = await c.req.json();

    // Query: find User where email = $body.email
    const found = Array.from(userStore.values()).find(r => r.email === body.email);

    if (found) {
      return c.json({ error: "Email already registered" }, 409);
    }

    // Hash: password (bcrypt)
    body.password = await bcrypt.hash(body.password, 10);

    // Insert into User
    const id = generateId();
    const now = new Date().toISOString();
    const record: User = {
      id,
      ...body,
      createdAt: now,
      updatedAt: now,
    };
    userStore.set(id, record);

    return c.json({ id: record.id, email: record.email, name: record.name, role: record.role }, 201);
  } catch (err: any) {
    console.error("Error in POST /auth/register:", err);
    return c.json({ error: err.message || "Internal server error" }, 500);
  }
}

// Authenticate and receive a JWT token
// Effects: DB (findOne on User)
// Proofs:
//   ✓ timing_safe: Hash comparison is constant-time via bcrypt.compare [by_construction]
async function handle_post__auth_login(c: any) {
  try {
    const body = await c.req.json();

    // Query: find User where email = $body.email
    const found = Array.from(userStore.values()).find(r => r.email === body.email);

    if (!found) {
      return c.json({ error: "Invalid credentials" }, 401);
    }

    // Compare hash: body.password against found.password
    const passwordValid = await bcrypt.compare(body.password, found.password);
    if (!passwordValid) {
      return c.json({ error: "Invalid credentials" }, 401);
    }

    // Sign JWT token (expires: 24h)
    const token = await sign({ sub: found.id, email: found.email, role: found.role, exp: Math.floor(Date.now() / 1000) + 86400 }, JWT_SECRET);

    return c.json({ token, user: { id: found.id, email: found.email, name: found.name, role: found.role } }, 200);
  } catch (err: any) {
    console.error("Error in POST /auth/login:", err);
    return c.json({ error: err.message || "Internal server error" }, 500);
  }
}

// Get the currently authenticated user's profile
// Effects: DB (findOne on User)
// Proofs:
//   ✓ auth_required: JWT middleware validates token before handler executes [by_constraint]
//   ✓ no_password_leak: Response explicitly excludes password field [by_construction]
async function handle_get__users_me(c: any) {
  try {

    // Query: find User where id = $c.get('user').sub
    const found = userStore.get(c.get('user').sub);

    if (!found) {
      return c.json({ error: "User not found" }, 404);
    }

    return c.json({ id: found.id, email: found.email, name: found.name, role: found.role }, 200);
  } catch (err: any) {
    console.error("Error in GET /users/me:", err);
    return c.json({ error: err.message || "Internal server error" }, 500);
  }
}

// List all published posts
// Effects: DB (findMany on Post)
async function handle_get__posts(c: any) {
  try {

    // Query: find all Post
    const results = Array.from(postStore.values());

    return c.json(results.filter(p => p.published), 200);
  } catch (err: any) {
    console.error("Error in GET /posts:", err);
    return c.json({ error: err.message || "Internal server error" }, 500);
  }
}

// Create a new post (authenticated)
// Effects: DB (insert into Post)
// Proofs:
//   ✓ auth_required: JWT middleware validates token before handler executes [by_constraint]
//   ✓ author_binding: authorId is set from JWT payload, not user input [by_construction]
async function handle_post__posts(c: any) {
  try {
    const body = await c.req.json();

    // Insert into Post
    const id = generateId();
    const now = new Date().toISOString();
    const record: Post = {
      id,
      ...body,
      createdAt: now,
      updatedAt: now,
    };
    postStore.set(id, record);

    return c.json(record, 201);
  } catch (err: any) {
    console.error("Error in POST /posts:", err);
    return c.json({ error: err.message || "Internal server error" }, 500);
  }
}

// Get a single post by ID
// Effects: DB (findOne on Post)
async function handle_get__posts__id(c: any) {
  try {
    const id = c.req.param("id");

    // Query: find Post where id = $id
    const found = postStore.get(id);

    if (!found) {
      return c.json({ error: "Post not found" }, 404);
    }

    return c.json(found, 200);
  } catch (err: any) {
    console.error("Error in GET /posts/:id:", err);
    return c.json({ error: err.message || "Internal server error" }, 500);
  }
}

// Delete a post (authenticated, owner only)
// Effects: DB (findOne on Post), DB (delete from Post)
// Proofs:
//   ✓ auth_required: JWT middleware validates token [by_constraint]
//   ✓ owner_only: Handler checks authorId matches JWT subject before deletion [by_construction]
async function handle_delete__posts__id(c: any) {
  try {
    const id = c.req.param("id");

    // Query: find Post where id = $id
    const found = postStore.get(id);

    if (!found) {
      return c.json({ error: "Post not found" }, 404);
    }

    if (found.authorId !== c.get('user').sub) {
      return c.json({ error: "Not authorized to delete this post" }, 403);
    }

    // Delete Post where id = $id
    const deleted = postStore.delete(id);
    if (!deleted) {
      return c.json({ error: "Post not found" }, 404);
    }

    return c.json({ message: "Post deleted" }, 200);
  } catch (err: any) {
    console.error("Error in DELETE /posts/:id:", err);
    return c.json({ error: err.message || "Internal server error" }, 500);
  }
}

// ── App Setup ─────────────────────────────────────────────

const app = new Hono();

app.use("*", cors({ origin: ["http://localhost:5173"] }));

app.use("*", loggerMiddleware());
app.use("*", rateLimitMiddleware());
// Note: auth applied globally — consider per-route application
app.use("*", authMiddleware());

app.get("/health", (c) => c.json({ status: "ok", timestamp: new Date().toISOString() }));

app.post("/auth/register", handle_post__auth_register);
app.post("/auth/login", handle_post__auth_login);
app.get("/users/me", authMiddleware(), handle_get__users_me);
app.get("/posts", handle_get__posts);
app.post("/posts", authMiddleware(), handle_post__posts);
app.get("/posts/:id", handle_get__posts__id);
app.delete("/posts/:id", authMiddleware(), handle_delete__posts__id);

// ── Start Server ──────────────────────────────────────────

const port = 3000;
console.log(`
  🔷 KLAR-IR compiled server running on http://localhost:${port}`);
console.log("  Routes:");
console.log("    POST   /auth/register");
console.log("    POST   /auth/login");
console.log("    GET    /users/me");
console.log("    GET    /posts");
console.log("    POST   /posts");
console.log("    GET    /posts/:id");
console.log("    DELETE /posts/:id");
console.log("");

export default {
  port,
  fetch: app.fetch,
};