import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { extractText, getDocumentProxy } from "unpdf";
import { beforeAll, describe, expect, it } from "vitest";
import { runAnalyzers } from "../../src/analyze/index.js";
import { suppressionNote } from "../../src/report/coverage.js";
import {
  BEYOND_INTENT_MEANING,
  buildReportModel,
  plainText,
  type ReportMeta,
  type ReportModel,
} from "../../src/report/model.js";
import { renderPdf } from "../../src/report/pdf.js";
import { createContext, extract } from "../../src/extract/index.js";
import { rank, toFinding } from "../../src/score/index.js";
import { WORKTREE, type Changeset, type Finding } from "../../src/types.js";

const changeset: Changeset = {
  range: { from: "abc123", to: WORKTREE, label: "vs origin/main" },
  files: [
    {
      path: "a.ts",
      status: "modified",
      hunks: [{ oldStart: 1, oldLines: 2, newStart: 1, newLines: 3 }],
      symbols: [],
    },
    {
      path: "b.ts",
      status: "modified",
      hunks: [{ oldStart: 5, oldLines: 1, newStart: 5, newLines: 1 }],
      symbols: [],
    },
  ],
};

const meta = (over: Partial<ReportMeta> = {}): ReportMeta => ({
  warnings: [],
  ...over,
});

const finding = (over: Partial<Finding> = {}): Finding => ({
  id: "effect_added:a.ts:network",
  tier: "verified",
  file: "a.ts",
  line: 3,
  title: "introduces a network effect",
  body: "This file previously had no network effect. It now does, at one site.",
  score: 60,
  evidence: [{ file: "a.ts", line: 3, excerpt: "return fetch(url);" }],
  ...over,
});

/**
 * Extracted text with all whitespace collapsed to single spaces. pdfkit wraps
 * long lines at word boundaries and unpdf renders each wrap as a newline, so
 * a phrase asserted verbatim could be split anywhere the layout happened to
 * break it; collapsing makes containment assertions layout-independent while
 * keeping word adjacency — which is exactly what these tests check.
 */
async function extracted(buf: Buffer): Promise<{ text: string; totalPages: number }> {
  const pdf = await getDocumentProxy(new Uint8Array(buf));
  const { text, totalPages } = await extractText(pdf, { mergePages: true });
  return { text: text.replace(/\s+/g, " "), totalPages };
}

const textOf = async (buf: Buffer): Promise<string> => (await extracted(buf)).text;

const RLO = "\u202E";

/**
 * A model exercising every honesty channel at once: a verified finding with
 * evidence, an inferred finding carrying a model claim, a standalone model
 * claim, a concealed character in an excerpt, an analyzer warning, and the
 * reach filter's suppression count.
 */
function fullModel(): ReportModel {
  return buildReportModel(
    changeset,
    [
      finding(),
      finding({
        id: "signature_changed:a.ts:3:send:send",
        tier: "inferred",
        title: "send changed its signature",
        claim: { summary: "hot path", reasoning: "This runs on every request." },
        evidence: [{ file: "a.ts", line: 3, excerpt: `cb(${RLO}n);` }],
      }),
      finding({
        id: "claim:0:c1",
        tier: "model",
        title: "may drop retries",
        body: "The retry loop looks removed.",
        evidence: [],
      }),
    ],
    meta({
      model: "claude-opus-5",
      warnings: ["the effects analyzer failed"],
      suppressed: 2,
    }),
  );
}

/** More findings than one page holds, each with a distinctive headline. */
function manyFindingsModel(): ReportModel {
  const findings = Array.from({ length: 40 }, (_, i) =>
    finding({
      id: `effect_added:f${i}.ts:network`,
      file: `f${i}.ts`,
      title: `probe ${i} sentinel`,
    }),
  );
  return buildReportModel(changeset, findings, meta());
}

const FOOTER = "Generated by urtext — every finding is labeled by its evidence tier";

describe("renderPdf honesty content", () => {
  it("carries the tier counts, disclosures, and evidence into extractable text", async () => {
    const text = await textOf(await renderPdf(fullModel()));
    expect(text).toContain("urtext review");
    expect(text).toContain("1 verified · 1 inferred · 1 model-only");
    expect(text).toContain("This review is partial.");
    expect(text).toContain("the effects analyzer failed");
    expect(text).toContain(suppressionNote(2));
    expect(text).toContain("return fetch(url);");
  });

  it("keeps a concealment label verbatim and carries no raw concealing character", async () => {
    const text = await textOf(await renderPdf(fullModel()));
    expect(text).toContain("cb([U+202E]n);");
    expect(text).not.toContain(RLO);
  });

  it("labels each evidence excerpt with its file:line, before-side marked", async () => {
    const text = await textOf(
      await renderPdf(
        buildReportModel(
          changeset,
          [
            finding({
              id: "guard_removed:old.ts:119:diff:if",
              file: "old.ts",
              line: 119,
              evidence: [
                { file: "old.ts", line: 119, excerpt: "if (seen) continue;", side: "before" },
              ],
            }),
          ],
          meta(),
        ),
      ),
    );
    expect(text).toContain("old.ts:119 (before)");
    expect(text).toContain("if (seen) continue;");
  });

  it("says nothing partial and nothing about filtering on a clean run", async () => {
    const text = await textOf(await renderPdf(buildReportModel(changeset, [finding()], meta())));
    expect(text).not.toContain("This review is partial.");
    expect(text).not.toContain("Filtered:");
  });

  it("says so, in the terminal's words, when there are no findings", async () => {
    const text = await textOf(await renderPdf(buildReportModel(changeset, [], meta())));
    expect(text).toContain("No findings. Nothing in this change tripped an analyzer.");
  });
});

describe("renderPdf model attribution", () => {
  it("keeps attribution adjacent to model-note prose, caution included", async () => {
    const text = await textOf(await renderPdf(fullModel()));
    // Adjacency, not mere co-presence: the attribution line immediately
    // precedes the prose it vouches for, so collapsed text concatenates them.
    expect(text).toContain("unverified · claude-opus-5 This runs on every request.");
    expect(text).toContain("The finding above is an analyzer's.");
  });

  it("attributes a standalone claim to the unnamed-model fallback when no model was recorded", async () => {
    const model = buildReportModel(
      changeset,
      [
        finding({
          id: "claim:0:c1",
          tier: "model",
          body: "The retry loop looks removed.",
          evidence: [],
        }),
      ],
      meta(),
    );
    const text = await textOf(await renderPdf(model));
    expect(text).toContain("unverified · an unnamed model The retry loop looks removed.");
    expect(text).toContain("Nothing mechanical corroborates this.");
  });
});

describe("renderPdf pagination", () => {
  it("renders every finding across pages — none silently truncated", async () => {
    const model = manyFindingsModel();
    const { text, totalPages } = await extracted(await renderPdf(model));
    expect(totalPages).toBeGreaterThan(1);
    for (const f of model.findings) {
      expect(text).toContain(plainText(f.title));
    }
  });

  it("numbers the findings in model order", async () => {
    const model = manyFindingsModel();
    const text = await textOf(await renderPdf(model));
    let last = -1;
    for (const [i, f] of model.findings.entries()) {
      const at = text.indexOf(`${i + 1}. ${f.glyph}`);
      expect(at).toBeGreaterThan(last);
      last = at;
    }
  });

  it("prints the footer on every page", async () => {
    const { text, totalPages } = await extracted(await renderPdf(manyFindingsModel()));
    expect(text.split(FOOTER).length - 1).toBe(totalPages);
  });
});

describe("renderPdf lazy load", () => {
  it("imports pdfkit dynamically and nowhere statically", () => {
    const source = readFileSync(
      fileURLToPath(new URL("../../src/report/pdf.ts", import.meta.url)),
      "utf8",
    );
    // The plan's constraint: a run without --export pdf loads nothing new.
    // A static import — type-only included, since a regex cannot prove
    // erasure — would defeat it silently; this pin makes that a test failure.
    expect(source).not.toMatch(/import[^;()]*from\s*["']pdfkit["']/);
    expect(source).not.toMatch(/require\(\s*["']pdfkit["']\s*\)/);
    expect(source).toMatch(/await import\(["']pdfkit["']\)/);
  });
});

/**
 * As `test/report/markdown.test.ts` does, this suite drives real analyzers
 * over a real repository and renders what they produce — a fixture written to
 * match today's id format cannot notice tomorrow's changing.
 */
describe("renderPdf against real analyzer output", () => {
  let repo: string;

  beforeAll(() => {
    repo = mkdtempSync(join(tmpdir(), "urtext-pdf-"));
    const git = (args: string[]) =>
      execFileSync("git", ["-c", "commit.gpgsign=false", ...args], { cwd: repo, stdio: "pipe" });
    git(["init", "-b", "main"]);
    git(["config", "user.email", "t@e.com"]);
    git(["config", "user.name", "T"]);
    mkdirSync(join(repo, "src"), { recursive: true });
    writeFileSync(
      join(repo, "src", "session.ts"),
      [
        "export function validate(token: string): { ok: boolean } {",
        "  if (!token) {",
        '    throw new Error("missing token");',
        "  }",
        "  return { ok: true };",
        "}",
        "",
      ].join("\n"),
    );
    writeFileSync(
      join(repo, "src", "caller.ts"),
      'import { validate } from "./session.js";\nexport const r = validate("x");\n',
    );
    git(["add", "-A"]);
    git(["commit", "-m", "first"]);
    // Removes a guard, widens the return type, and adds a network effect.
    writeFileSync(
      join(repo, "src", "session.ts"),
      [
        "export async function validate(token: string): Promise<{ ok: boolean } | null> {",
        "  const res = await fetch(`https://auth.example.com/${token}`);",
        "  return res.ok ? { ok: true } : null;",
        "}",
        "",
      ].join("\n"),
    );
  });

  it("carries every real finding's headline and evidence into the document", async () => {
    const cs = await extract(repo);
    const findings = rank(await runAnalyzers(cs, createContext(repo, cs.range)));
    const model = buildReportModel(cs, findings, { warnings: [] });
    const text = await textOf(await renderPdf(model));

    expect(model.findings.length).toBeGreaterThan(0);
    expect(text).toContain("guard was removed");
    expect(text).toContain("network effect");
    for (const f of model.findings) {
      expect(text).toContain(plainText(f.headline).replace(/\s+/g, " "));
    }
    for (const e of model.findings.flatMap((f) => f.evidence)) {
      expect(text).toContain(plainText(e.excerpt).replace(/\s+/g, " "));
    }
  });
});

describe("renderPdf beyond stated intent", () => {
  it("carries the mark and the legend into extractable text", async () => {
    const model = buildReportModel(
      changeset,
      [finding({ tier: "inferred", beyondIntent: true, claim: { summary: "s", reasoning: "r" } })],
      meta({ model: "claude-opus-5" }),
    );
    const text = await textOf(await renderPdf(model));
    expect(text).toContain("[inferred] (beyond stated intent)");
    // Collapsed whitespace, so assert on the sentence the same way the other
    // disclosure assertions in this file do.
    expect(text).toContain(BEYOND_INTENT_MEANING.replace(/\s+/g, " "));
  });

  it("renders neither the mark nor the legend when nothing is marked", async () => {
    const text = await textOf(await renderPdf(buildReportModel(changeset, [finding()], meta())));
    expect(text).not.toContain("beyond stated intent");
  });
});

/**
 * One real citation finding, composed by `toFinding` rather than written out
 * here, so this surface is checked against the copy the scorer actually
 * produces and not against a restatement of it.
 */
const citationFinding = (): Finding =>
  toFinding({
    id: "citation_rot:docs/a.md:1:content_drift",
    kind: "citation_rot",
    file: "docs/a.md",
    line: 1,
    detail: {
      rot: "content_drift",
      citedFile: "src/a.ts",
      citedLine: 1,
      was: "export const limit = 1;",
      now: "export const limit = 99;",
      baseline: "3f2a1c9",
    },
    evidence: [
      { file: "docs/a.md", line: 1, excerpt: "The limit is set at src/a.ts:1.", side: "after" },
      { file: "src/a.ts", line: 1, excerpt: "export const limit = 99;", side: "after" },
    ],
  });

describe("renderPdf citation findings", () => {
  it("carries a citation finding's headline, body, and both evidence refs into extractable text", async () => {
    const text = await textOf(
      await renderPdf(buildReportModel(changeset, [citationFinding()], meta())),
    );
    expect(text).toContain("docs/a.md:1 — cites `src/a.ts:1`, which no longer reads the same");
    expect(text).toContain(
      "The citation still resolves to a line; it no longer resolves to the same content.",
    );
    expect(text).toContain("docs/a.md:1 The limit is set at src/a.ts:1.");
    expect(text).toContain("src/a.ts:1 export const limit = 99;");
  });
});
