// ============================================================
// KLAR-IR → TypeScript Transpiler
// Emits real, runnable server code from the semantic graph.
// Currently targets Hono (lightweight, modern, runs everywhere).
// ============================================================

import {
  KlarGraph, KlarType, ModelDef, RouteDef, MiddlewareDef,
  Field, Constraint, Effect, GraphConfig, T
} from "./types.js";
import { HandlerStep } from "./builder.js";

interface EmitContext {
  imports: Set<string>;
  helpers: Set<string>;
  config: GraphConfig;
}

// --- Main entry point ---
export function emit(graph: KlarGraph & { _routes: any[]; _middleware: any[] }): string {
  const ctx: EmitContext = {
    imports: new Set(),
    helpers: new Set(),
    config: graph.config,
  };

  const sections: string[] = [];

  // Header
  sections.push(emitHeader(graph));

  // Imports (populated as we emit other sections)
  // We'll insert this at position 1 after everything else is emitted

  // Types from models
  sections.push(emitModelTypes(graph, ctx));

  // Validation helpers
  sections.push(emitValidationHelpers(graph, ctx));

  // Middleware
  sections.push(emitMiddleware(graph._middleware, ctx));

  // In-memory store (for prototype)
  sections.push(emitStore(graph, ctx));

  // Route handlers
  sections.push(emitRoutes(graph._routes, graph._middleware, ctx));

  // App setup and start
  sections.push(emitAppSetup(graph, ctx));

  // Assemble with imports
  const imports = emitImports(ctx);
  return [imports, ...sections].join("\n\n");
}

function emitHeader(graph: KlarGraph): string {
  return [
    "// ═══════════════════════════════════════════════════════════",
    `// ${graph.name}`,
    `// Generated by KLAR-IR Transpiler v${graph.version}`,
    `// Generated at: ${new Date().toISOString()}`,
    "//",
    "// This file was compiled from a KLAR-IR semantic graph.",
    "// Do not edit manually — modify the IR and recompile.",
    "// ═══════════════════════════════════════════════════════════",
  ].join("\n");
}

function emitImports(ctx: EmitContext): string {
  const lines: string[] = [];
  lines.push(`import { Hono } from "hono";`);
  lines.push(`import { cors } from "hono/cors";`);

  if (ctx.imports.has("jwt")) {
    lines.push(`import { sign, verify } from "hono/jwt";`);
  }
  if (ctx.imports.has("bcrypt")) {
    lines.push(`import bcrypt from "bcryptjs";`);
  }

  lines.push(`import { HTTPException } from "hono/http-exception";`);

  return lines.join("\n");
}

function emitModelTypes(graph: KlarGraph, ctx: EmitContext): string {
  const lines: string[] = [];
  lines.push("// ── Models ────────────────────────────────────────────────");

  for (const [name, model] of graph.models) {
    lines.push("");
    lines.push(`export interface ${name} {`);
    for (const field of model.fields) {
      const tsType = klarTypeToTS(field.type);
      const optional = field.type.kind === "option" ? "?" : "";
      lines.push(`  ${field.name}${optional}: ${tsType};`);
    }
    lines.push("}");

    // Emit creation type (without auto-generated fields)
    const autoFields = new Set(["id", "createdAt", "updatedAt"]);
    const createFields = model.fields.filter(f => !autoFields.has(f.name));
    if (createFields.length < model.fields.length) {
      lines.push("");
      lines.push(`export interface Create${name}Input {`);
      for (const field of createFields) {
        const tsType = klarTypeToTS(field.type);
        const optional = field.type.kind === "option" ? "?" : "";
        lines.push(`  ${field.name}${optional}: ${tsType};`);
      }
      lines.push("}");
    }
  }

  return lines.join("\n");
}

function emitValidationHelpers(graph: KlarGraph, ctx: EmitContext): string {
  const lines: string[] = [];
  lines.push("// ── Validation (from KLAR-IR constraints) ─────────────────");
  lines.push("");

  lines.push("interface ValidationError {");
  lines.push("  field: string;");
  lines.push("  message: string;");
  lines.push("}");
  lines.push("");

  // Emit a validator for each model's create input
  for (const [name, model] of graph.models) {
    const autoFields = new Set(["id", "createdAt", "updatedAt"]);
    const fields = model.fields.filter(f => !autoFields.has(f.name));
    const hasConstraints = fields.some(f => f.constraints.length > 0);

    lines.push(`function validate${name}(input: Record<string, any>): ValidationError[] {`);
    lines.push("  const errors: ValidationError[] = [];");

    for (const field of fields) {
      if (field.type.kind !== "option") {
        lines.push(`  if (input.${field.name} === undefined || input.${field.name} === null) {`);
        lines.push(`    errors.push({ field: "${field.name}", message: "${field.name} is required" });`);
        lines.push(`  }`);
      }

      for (const c of field.constraints) {
        lines.push(`  // Constraint: ${c.message}`);
        const cond = constraintToCondition(field.name, c);
        if (cond) {
          lines.push(`  if (input.${field.name} !== undefined && ${cond}) {`);
          lines.push(`    errors.push({ field: "${field.name}", message: "${c.message}" });`);
          lines.push(`  }`);
        }
      }
    }

    lines.push("  return errors;");
    lines.push("}");
    lines.push("");
  }

  // Emit route-level input validators
  for (const route of graph.routes) {
    const allFields = [
      ...(route.input.body || []),
      ...(route.input.query || []),
      ...(route.input.params || []),
    ];
    const fieldsWithConstraints = allFields.filter(f => f.constraints.length > 0);
    if (fieldsWithConstraints.length === 0) continue;

    const fnName = `validateRoute_${route.method}_${route.path.replace(/[/:]/g, "_")}`;
    lines.push(`function ${fnName}(input: Record<string, any>): ValidationError[] {`);
    lines.push("  const errors: ValidationError[] = [];");
    for (const field of fieldsWithConstraints) {
      for (const c of field.constraints) {
        const cond = constraintToCondition(field.name, c);
        if (cond) {
          lines.push(`  if (input.${field.name} !== undefined && ${cond}) {`);
          lines.push(`    errors.push({ field: "${field.name}", message: "${c.message}" });`);
          lines.push(`  }`);
        }
      }
    }
    lines.push("  return errors;");
    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
}

function constraintToCondition(fieldName: string, c: Constraint): string | null {
  const v = `input.${fieldName}`;
  switch (c.op) {
    case "!=": return `${v} === ${JSON.stringify(c.value)}`;
    case "==": return `${v} !== ${JSON.stringify(c.value)}`;
    case ">":  return `${v} <= ${c.value}`;
    case "<":  return `${v} >= ${c.value}`;
    case ">=": return `${v} < ${c.value}`;
    case "<=": return `${v} > ${c.value}`;
    case "matches":
      return `!/${c.pattern}/.test(String(${v}))`;
    case "length_between": {
      const parts: string[] = [];
      if (c.min !== undefined) parts.push(`String(${v}).length < ${c.min}`);
      if (c.max !== undefined) parts.push(`String(${v}).length > ${c.max}`);
      return parts.join(" || ") || null;
    }
    case "in":
      return `!${JSON.stringify(c.value)}.includes(${v})`;
    case "not_in":
      return `${JSON.stringify(c.value)}.includes(${v})`;
    default:
      return null;
  }
}

function emitMiddleware(middleware: (MiddlewareDef & { _type: string })[], ctx: EmitContext): string {
  const lines: string[] = [];
  lines.push("// ── Middleware ─────────────────────────────────────────────");

  for (const mw of middleware.sort((a, b) => a.order - b.order)) {
    lines.push("");
    switch (mw._type) {
      case "rate_limit":
        lines.push(emitRateLimitMiddleware(mw));
        break;
      case "jwt_auth":
        ctx.imports.add("jwt");
        lines.push(emitAuthMiddleware(mw));
        break;
      case "logger":
        lines.push(emitLoggerMiddleware(mw));
        break;
      case "cors":
        // handled in app setup
        break;
      default:
        lines.push(`// TODO: custom middleware '${mw.name}'`);
    }
  }

  return lines.join("\n");
}

function emitRateLimitMiddleware(mw: MiddlewareDef): string {
  const windowMs = mw.config.windowMs || 60000;
  const max = mw.config.maxRequests || 100;

  return `// Rate limiter: ${max} requests per ${windowMs}ms window
const rateLimitStore = new Map<string, { count: number; resetAt: number }>();

function rateLimitMiddleware() {
  return async (c: any, next: any) => {
    const key = c.req.header("x-forwarded-for") || "unknown";
    const now = Date.now();
    const entry = rateLimitStore.get(key);

    if (!entry || now > entry.resetAt) {
      rateLimitStore.set(key, { count: 1, resetAt: now + ${windowMs} });
    } else if (entry.count >= ${max}) {
      c.header("Retry-After", String(Math.ceil((entry.resetAt - now) / 1000)));
      return c.json({ error: "Rate limit exceeded" }, 429);
    } else {
      entry.count++;
    }

    await next();
  };
}`;
}

function emitAuthMiddleware(mw: MiddlewareDef): string {
  const secret = mw.config.secret || "process.env.JWT_SECRET";

  return `// JWT Auth middleware
const JWT_SECRET = ${secret.startsWith("process.env") ? secret : `"${secret}"`};

function authMiddleware() {
  return async (c: any, next: any) => {
    const authHeader = c.req.header("Authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return c.json({ error: "Missing or invalid authorization header" }, 401);
    }

    try {
      const token = authHeader.slice(7);
      const payload = await verify(token, JWT_SECRET);
      c.set("user", payload);
      await next();
    } catch {
      return c.json({ error: "Invalid or expired token" }, 401);
    }
  };
}`;
}

function emitLoggerMiddleware(mw: MiddlewareDef): string {
  return `// Request logger
function loggerMiddleware() {
  return async (c: any, next: any) => {
    const start = Date.now();
    const method = c.req.method;
    const path = c.req.path;

    await next();

    const duration = Date.now() - start;
    const status = c.res.status;
    console.log(\`\${method} \${path} → \${status} (\${duration}ms)\`);
  };
}`;
}

function emitStore(graph: KlarGraph, ctx: EmitContext): string {
  const lines: string[] = [];
  lines.push("// ── In-Memory Store (swap for real DB in production) ──────");
  lines.push("");

  for (const [name, model] of graph.models) {
    lines.push(`const ${name.toLowerCase()}Store = new Map<string, ${name}>();`);
  }

  lines.push("");
  lines.push("function generateId(): string {");
  lines.push("  return crypto.randomUUID();");
  lines.push("}");

  return lines.join("\n");
}

function emitRoutes(
  routes: (RouteDef & { _handlerLogic: HandlerStep[] })[],
  middleware: (MiddlewareDef & { _type: string })[],
  ctx: EmitContext
): string {
  const lines: string[] = [];
  lines.push("// ── Route Handlers ────────────────────────────────────────");

  for (const route of routes) {
    lines.push("");
    lines.push(`// ${route.provenance.instruction}`);
    if (route.effects.length > 0) {
      lines.push(`// Effects: ${route.effects.map(e => e.kind + (e.detail ? ` (${e.detail})` : "")).join(", ")}`);
    }
    if (route.proofs.length > 0) {
      lines.push(`// Proofs:`);
      for (const p of route.proofs) {
        lines.push(`//   ✓ ${p.property}: ${p.detail} [${p.kind}]`);
      }
    }

    lines.push(emitHandler(route, ctx));
  }

  return lines.join("\n");
}

function emitHandler(route: RouteDef & { _handlerLogic: HandlerStep[] }, ctx: EmitContext): string {
  const lines: string[] = [];
  const handlerName = `handle_${route.method.toLowerCase()}_${route.path.replace(/[/:]/g, "_")}`;

  lines.push(`async function ${handlerName}(c: any) {`);
  lines.push("  try {");

  // Extract inputs
  if (route.input.params?.length) {
    for (const p of route.input.params) {
      lines.push(`    const ${p.name} = c.req.param("${p.name}");`);
    }
  }
  if (route.input.body?.length) {
    lines.push("    const body = await c.req.json();");
  }
  if (route.input.query?.length) {
    for (const q of route.input.query) {
      lines.push(`    const ${q.name} = c.req.query("${q.name}");`);
    }
  }

  // Emit handler logic from steps
  let resultVar = "result";
  for (const step of route._handlerLogic) {
    lines.push("");
    lines.push(...emitStep(step, ctx).map(l => "    " + l));
  }

  lines.push("  } catch (err: any) {");
  lines.push(`    console.error("Error in ${route.method} ${route.path}:", err);`);
  lines.push(`    return c.json({ error: err.message || "Internal server error" }, 500);`);
  lines.push("  }");
  lines.push("}");

  return lines.join("\n");
}

function emitStep(step: HandlerStep, ctx: EmitContext): string[] {
  const lines: string[] = [];
  const d = step.detail;

  switch (step.action) {
    case "validate": {
      lines.push(`// Validate: ${d.field} — ${d.check}`);
      lines.push(`if (!${d.check}) {`);
      lines.push(`  return c.json({ error: "Validation failed for ${d.field}" }, 400);`);
      lines.push(`}`);
      break;
    }

    case "db_query": {
      const storeName = `${d.model.toLowerCase()}Store`;
      if (d.operation === "findOne" && d.where) {
        const [key, val] = Object.entries(d.where)[0];
        const valExpr = String(val).startsWith("$") ? String(val).slice(1) : `"${val}"`;
        lines.push(`// Query: find ${d.model} where ${key} = ${val}`);
        if (key === "id") {
          lines.push(`const found = ${storeName}.get(${valExpr});`);
        } else {
          lines.push(`const found = Array.from(${storeName}.values()).find(r => r.${key} === ${valExpr});`);
        }
      } else if (d.operation === "findMany") {
        lines.push(`// Query: find all ${d.model}`);
        lines.push(`const results = Array.from(${storeName}.values());`);
      } else {
        lines.push(`// Query: ${d.operation} on ${d.model}`);
        lines.push(`const results = Array.from(${storeName}.values());`);
      }
      break;
    }

    case "db_insert": {
      const storeName = `${d.model.toLowerCase()}Store`;
      lines.push(`// Insert into ${d.model}`);
      lines.push(`const id = generateId();`);
      lines.push(`const now = new Date().toISOString();`);
      lines.push(`const record: ${d.model} = {`);
      lines.push(`  id,`);
      lines.push(`  ...body,`);
      lines.push(`  createdAt: now,`);
      lines.push(`  updatedAt: now,`);
      lines.push(`};`);
      lines.push(`${storeName}.set(id, record);`);
      break;
    }

    case "db_update": {
      const storeName = `${d.model.toLowerCase()}Store`;
      const [key, val] = Object.entries(d.where)[0];
      const valExpr = String(val).startsWith("$") ? String(val).slice(1) : `"${val}"`;
      lines.push(`// Update ${d.model} where ${key} = ${val}`);
      lines.push(`const toUpdate = ${storeName}.get(${valExpr});`);
      lines.push(`if (!toUpdate) {`);
      lines.push(`  return c.json({ error: "${d.model} not found" }, 404);`);
      lines.push(`}`);
      lines.push(`const updated = { ...toUpdate, ...body, updatedAt: new Date().toISOString() };`);
      lines.push(`${storeName}.set(${valExpr}, updated);`);
      break;
    }

    case "db_delete": {
      const storeName = `${d.model.toLowerCase()}Store`;
      const [key, val] = Object.entries(d.where)[0];
      const valExpr = String(val).startsWith("$") ? String(val).slice(1) : `"${val}"`;
      lines.push(`// Delete ${d.model} where ${key} = ${val}`);
      lines.push(`const deleted = ${storeName}.delete(${valExpr});`);
      lines.push(`if (!deleted) {`);
      lines.push(`  return c.json({ error: "${d.model} not found" }, 404);`);
      lines.push(`}`);
      break;
    }

    case "hash": {
      ctx.imports.add("bcrypt");
      lines.push(`// Hash: ${d.field} (${d.algorithm})`);
      lines.push(`body.${d.field} = await bcrypt.hash(body.${d.field}, 10);`);
      break;
    }

    case "compare_hash": {
      ctx.imports.add("bcrypt");
      lines.push(`// Compare hash: ${d.input} against ${d.stored}`);
      lines.push(`const passwordValid = await bcrypt.compare(${d.input}, ${d.stored});`);
      lines.push(`if (!passwordValid) {`);
      lines.push(`  return c.json({ error: "Invalid credentials" }, 401);`);
      lines.push(`}`);
      break;
    }

    case "sign_token": {
      ctx.imports.add("jwt");
      const payloadEntries = Object.entries(d.payload)
        .map(([k, v]) => `${k}: ${String(v).startsWith("$") ? String(v).slice(1) : `"${v}"`}`)
        .join(", ");
      lines.push(`// Sign JWT token (expires: ${d.expiresIn})`);
      lines.push(`const token = await sign({ ${payloadEntries}, exp: Math.floor(Date.now() / 1000) + ${parseExpiry(d.expiresIn)} }, JWT_SECRET);`);
      break;
    }

    case "respond": {
      lines.push(`return c.json(${d.body === "result" ? "record || results || found" : d.body}, ${d.status});`);
      break;
    }

    case "respond_error": {
      lines.push(`return c.json({ error: "${d.message}" }, ${d.status});`);
      break;
    }

    case "branch": {
      lines.push(`if (${d.condition}) {`);
      if (d.then) {
        for (const s of d.then) {
          lines.push(...emitStep(s, ctx).map(l => "  " + l));
        }
      }
      if (d.else) {
        lines.push(`} else {`);
        for (const s of d.else) {
          lines.push(...emitStep(s, ctx).map(l => "  " + l));
        }
      }
      lines.push(`}`);
      break;
    }

    default:
      lines.push(`// Unknown step: ${step.action}`);
  }

  return lines;
}

function parseExpiry(exp: string): number {
  const match = exp.match(/^(\d+)(h|m|d)$/);
  if (!match) return 86400;
  const [, n, unit] = match;
  const num = parseInt(n, 10);
  switch (unit) {
    case "h": return num * 3600;
    case "m": return num * 60;
    case "d": return num * 86400;
    default: return 86400;
  }
}

function emitAppSetup(graph: KlarGraph & { _routes: any[]; _middleware: any[] }, ctx: EmitContext): string {
  const lines: string[] = [];
  lines.push("// ── App Setup ─────────────────────────────────────────────");
  lines.push("");
  lines.push("const app = new Hono();");
  lines.push("");

  // CORS
  const corsMw = graph._middleware.find((m: any) => m._type === "cors");
  if (corsMw) {
    const origins = corsMw.config.origins?.join('", "') || "*";
    lines.push(`app.use("*", cors({ origin: ["${origins}"] }));`);
    lines.push("");
  }

  // Global middleware
  const globalMw = graph._middleware
    .filter((m: any) => m.appliesTo === "all" && m._type !== "cors")
    .sort((a: any, b: any) => a.order - b.order);

  for (const mw of globalMw) {
    switch ((mw as any)._type) {
      case "logger":
        lines.push(`app.use("*", loggerMiddleware());`);
        break;
      case "rate_limit":
        lines.push(`app.use("*", rateLimitMiddleware());`);
        break;
      case "jwt_auth":
        // Auth is typically per-route, but if global:
        lines.push(`// Note: auth applied globally — consider per-route application`);
        lines.push(`app.use("*", authMiddleware());`);
        break;
    }
  }
  lines.push("");

  // Health check
  lines.push(`app.get("/health", (c) => c.json({ status: "ok", timestamp: new Date().toISOString() }));`);
  lines.push("");

  // Routes
  const authMw = graph._middleware.find((m: any) => m._type === "jwt_auth");

  for (const route of graph._routes) {
    const handlerName = `handle_${route.method.toLowerCase()}_${route.path.replace(/[/:]/g, "_")}`;
    const method = route.method.toLowerCase();
    const path = route.path.replace(/:([a-zA-Z_]+)/g, ":$1");

    // Check if this route uses auth middleware
    const usesAuth = authMw && route.middleware.includes(authMw.id);

    if (usesAuth) {
      lines.push(`app.${method}("${path}", authMiddleware(), ${handlerName});`);
    } else {
      lines.push(`app.${method}("${path}", ${handlerName});`);
    }
  }

  lines.push("");
  lines.push("// ── Start Server ──────────────────────────────────────────");
  lines.push("");
  lines.push(`const port = ${graph.config.port};`);
  lines.push(`console.log(\`\n  🔷 KLAR-IR compiled server running on http://localhost:\${port}\`);`);
  lines.push(`console.log("  Routes:");`);

  for (const route of graph._routes) {
    lines.push(`console.log("    ${route.method.padEnd(6)} ${route.path}");`);
  }

  lines.push(`console.log("");`);
  lines.push("");
  lines.push("export default {");
  lines.push(`  port,`);
  lines.push("  fetch: app.fetch,");
  lines.push("};");

  return lines.join("\n");
}

// --- Type mapping ---
function klarTypeToTS(type: KlarType): string {
  switch (type.kind) {
    case "primitive":
      switch (type.name) {
        case "str": return "string";
        case "int": case "float": return "number";
        case "bool": return "boolean";
        case "void": return "void";
        case "timestamp": return "string"; // ISO string
      }
    case "option": return `${klarTypeToTS(type.inner)} | null`;
    case "result": return `{ ok: ${klarTypeToTS(type.ok)} } | { err: ${klarTypeToTS(type.err)} }`;
    case "array": return `${klarTypeToTS(type.element)}[]`;
    case "map": return `Record<${klarTypeToTS(type.key)}, ${klarTypeToTS(type.value)}>`;
    case "ref": return type.structName;
    case "union": return type.variants.map(v => `{ tag: "${v.tag}" }`).join(" | ");
    case "refined": return klarTypeToTS(type.base);
    default: return "any";
  }
}
